# Generated by Django 4.2.1 on 2023-05-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на WhatsApp')),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на Telegram')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст о нас')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
